### PR TITLE
build: introduce TypeScript to the project

### PR DESCRIPTION
**Pull request by kopach**
Note: includes also changes from https://github.com/a7ul/react-webcomponentify/pull/5 & https://github.com/a7ul/react-webcomponentify/pull/6
So, those should be merged first

### CODE REVIEW

**Comment by kopach** [comment]
hi @a7ul. Please, let me know if you're interested in all those changes from PRs https://github.com/a7ul/react-webcomponentify/pull/5, https://github.com/a7ul/react-webcomponentify/pull/6 & https://github.com/a7ul/react-webcomponentify/pull/7
I'm going to use WebComponents with React quite intensively in the nearest future, so going to update this lib, if needed. If you're interested in any closer cooperation - let me know. Otherwise, if this project is low priority for you now, and you won't have time on it – I will go with my fork.

**Comment by a7ul** [comment]
Wow! Thanks a lot. 
Would you be interested in becoming a maintainer too ?

**Comment by kopach** [comment]
@a7ul, yes, please. That would simplify things :)

**Comment by a7ul** [comment]
sent an invite :)

**Pull request merged**
